import React, { useState, useEffect } from 'react';
import axios from 'axios';
import UploadVideo from './components/UploadVideo';
import VideoList from './components/VideoList';
import './App.css';

function App() {
  const [videos, setVideos] = useState([]);

  // Função para carregar a lista de vídeos da API
  const fetchVideos = async () => {
    try {
      const response = await axios.get('http://localhost:5000/api/videos'); // URL da API
      setVideos(response.data);
    } catch (error) {
      console.error('Erro ao buscar vídeos', error);
    }
  };

  useEffect(() => {
    fetchVideos();
  }, []);

  return (
    <div className="App">
      <h1>Sistema de Armazenamento de Vídeos DVR</h1>
      <UploadVideo fetchVideos={fetchVideos} />
      <VideoList videos={videos} />
    </div>
  );
}

export default App;
